modifications

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -1,23 +1,19 @@
 #!/bin/bash
 
 source $OPENSHIFT_CARTRIDGE_SDK_BASH
-NEO4J_BIN_DIR=${OPENSHIFT_NEO4J_DIR}/versions/1.0/jelasticbasic/bin
+JELASTICBASIC_BIN_DIR=${OPENSHIFT_JELASTICBASIC_DIR}/versions/1.0/jelasticbasic/bin
 
-
-NEO4J_CLI="-host $OPENSHIFT_NEO4J_DB_HOST -port $OPENSHIFT_NEO4J_DB_PORT"
 
 function is_running() {
-    if [ -f $PID ]; then
-        return 0
-    fi
-    return 1
+    pgrep jelasticbasic  > /dev/null 2>&1; e
+    return $?
 }
 
 function status() {
     if [ is_running ]; then
-        client_result "Neo4j is running"
+        client_result "Jelasticbasic is running"
     else
-        client_result "Neo4J is not running"
+        client_result "Jelasticbasic is not running"
     fi
 }
 
@@ -26,22 +22,18 @@ function start() {
         exit 0
     fi
 
-    ${NEO4J_BIN_DIR}/neo4j start -host $OPENSHIFT_NEO4J_DB_HOST -port $OPENSHIFT_NEO4J_DB_PORT
+    ${JELASTICBASIC_BIN_DIR}/jelasticbasic -p $OPENSHIFT_NEO4J_APP_PORT -r ${OPENSHIFT_JELASTICBASIC_DIR}/versions/
 
     ret=$?
     if [ $ret -ne 0 ]; then
-        echo "Neo4j failed to start - $ret" 1>&2
+        echo "Jelasticbasic failed to start - $ret" 1>&2
         exit $ret
     fi
 }
 
 function stop() {
     if (is_running); then
-        ${NEO4J_BIN_DIR}/neo4j stop
-        if [ $? -eq 0 ]; then
-            exit 0
-        fi
-        exit 1
+        killall -9 jelasticbasic
     fi
 }
 
